kind: pipeline
name: default
workspace:
  base: /go
  path: src/goTodoAPI
steps:
  - name: build
    image: golang
    commands:
      - go env
      - pwd
      - go get
  - name: run
    image: golang
    commands:
      - go build -o output
      - chmod +x output
      - ./output