package main

import (
	"github.com/caarlos0/env"
	log "github.com/sirupsen/logrus"
	"github.com/swaggo/http-swagger"
	_ "github.com/swaggo/http-swagger/example/go-chi/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/lacazethomas/goTodo/app"
	"github.com/lacazethomas/goTodo/config"
)


//TODO: Better file organization

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v2
func main() {

	log.SetFormatter(&log.JSONFormatter{})
	config := config.DB{}
	err := env.Parse(&config)
	if err != nil {
		log.Println("Can not get env variable")
	}
	app := &app.App{}
	app.Initialize(config)
	app.Run(":8000")
}
